### ISSUE TITLE
TypeScript support no longer seems to work?

### ISSUE THREAD

**Issue by whomwah** [mopidy/mopidy.js#40]
@jodal It looks like this commit seems to have broken things? unless it's just for me? This is change where the namespaces were switched from `PascalCase` to `lowercase`:

[Lowercase namespace names](https://github.com/mopidy/mopidy.js/commit/87cfa03c0b8e55a04a3d97736af49c7935486bf4)

These are the lines in question:
* https://github.com/mopidy/mopidy.js/blob/master/src/mopidy.d.ts#L84
* https://github.com/mopidy/mopidy.js/blob/master/src/mopidy.d.ts#L594

<img width="890" alt="Screenshot 2021-01-18 at 13 24 20" src="https://user-images.githubusercontent.com/2031/104920956-86671f80-5990-11eb-8904-5e3e05a34985.png">

**Comment by jodal** [comment]
I have to admit that I've not familiar with namespaces in TypeScript, and see now that all the documentation on it use CamelCase naming.

Does your code work if you lowercase `Mopidy` too? `mopidy` is the name of the top-level TypeScript namespace. `Mopidy` is the name of the class.

**Comment by whomwah** [comment]
Changing my code to `mopidy` doesn't fix things. Reverting the commit above makes it work again. I assume (as I am also no TypesFile expert) that by calling the namespace `Mopidy` (PascalCase) means that it is _also_ exported and therefore makes `.models` for instance available a bit like class methods `Klass.method`. I know that's not actually true, but that's how I think of it.

**Comment by svedue** [comment]
The mopidy namespace is not exported.
I fixed it locally by editing line 84 
`declare namespace mopidy { `
to 
`export declare namespace mopidy {`.
Then you can use
`import { mopidy } from "mopidy";`
and reference model with fqn:
`trackDurationString(track: mopidy.models.Track)`

**Comment by whomwah** [comment]
One question on the above though. This seems every limiting and not quite right. I used to be able to do this before the change:
```js
import Mopidy from 'mopidy'

const mopidy = new Mopidy({
  webSocketUrl: `ws://${mopidyUrl}:${mopidyPort}/mopidy/ws/`
})
const track: Mopidy.models.TlTrack = mopidy.playback.getCurrentTrack()
```

Now I'd have to do something like:
```js
import Mopidy, { mopidy } from 'mopidy'

const mopidyInstance = new Mopidy({
  webSocketUrl: `ws://${mopidyUrl}:${mopidyPort}/mopidy/ws/`
})
const track: mopidy.models.TlTrack = mopidyInstance.playback.getCurrentTrack()
```

Have I missed something.

**Comment by jodal** [comment]
I still don't feel entirely up to speed on external TypeScript declarations, but given that:

1. All the examples in the TypeScript documentation seem to use namespaces with an uppercase initial letter.
2. Only having to import one thing is nice.
3. Not having to import another thing that collides with the usual name of the `Mopidy` instance is nice.

I'm leaning towards reverting at least the top-most namespace to be named `Mopidy` instead of `mopidy`. Does that sound like an OK solution?

On an aside, I'd love to have a TypeScript linter and to have an example using TypeScript in the repo so that I have an easy way of testing these changes before releasing them. PRs welcome!

**Comment by whomwah** [comment]
I know DefinitelyTyped require tests for the definition file, but TBH I'm not super sure how that works. I'll look into it though, as something like that sounds like what you're looking for.

**Comment by jodal** [comment]
Fixed by #45.
